const patchTwo = [
  {id: "Pad-1",
  triggerKey: "Q",
  jskeycode: 81,
  name: 'Loop 1',
  icon: "",
  url: "/tr808/loop1-85bpm.ogg"},
  {id: "Pad-2",
  triggerKey: "W",
  jskeycode: 87,
  name: 'Loop 2',
  icon: "",
  url: "/tr808/loop2-85bpm.ogg"},
  {id: "Pad-3",
  triggerKey: "E",
  jskeycode: 69,
  name: 'Loop 3',
  icon: "",
  url: "/tr808/loop3-85bpm.ogg"},
  {id: "Pad-4",
  triggerKey: "A",
  jskeycode: 65,
  name: 'Loop 4',
  icon: "",
  url: "/tr808/loop4-85bpm.ogg"},
  {id: "Pad-5",
  triggerKey: "S",
  jskeycode: 83,
  name: 'Cymbal',
  icon: "",
  url: "/tr808/cymbal.ogg"},
  {id: "Pad-6",
  triggerKey: "D",
  jskeycode: 68,
  name: 'Snare',
  icon: "",
  url: "/tr808/snare.ogg"},
  {id: "Pad-7",
  triggerKey: "Z",
  jskeycode: 90,
  name: 'Kick',
  icon: "",
  url: "/tr808/kick.ogg"},
  {id: "Pad-8",
  triggerKey: "X",
  jskeycode: 88,
  name: 'Power Snare',
  icon: "",
  url: "/tr808/power-snare.ogg"},
  {id: "Pad-9",
  triggerKey: "C",
  jskeycode: 67,
  name: 'Open Hihat',
  icon: "",
  url: "/tr808/open-snare.ogg"} 
];

